# Generated by Django 3.2.9 on 2022-06-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
